markdown: kramdown
highlighter: rouge
permalink: pretty
excerpt_separator: <!--more-->
title: Anatoli Makarevich on web
url: http://makaroni4.com
author:
  name: Anatoli Makarevich
plugins:
  - jekyll-feed
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: "code-highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
